import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';
import { append, calculate, demonstration, emptyState, publicView, draftFor } from '../../../lib/core.mjs';
export const dynamic='force-dynamic';
const config=env as unknown as {DB:D1Database,ALLOW_OWNER_BOOTSTRAP?:string,PUBLIC_ORIGIN?:string};
function response(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store'}});}
function eventId(req:Request){const id=new URL(req.url).searchParams.get('event')||'practice';if(!['practice','rehearsal','production'].includes(id))throw Error('イベントが不正です');return id;}
async function read(id:string){const row=await config.DB.prepare('SELECT payload,version FROM event_store WHERE id=?').bind(id).first<{payload:string,version:number}>();return {state:row?JSON.parse(row.payload):id==='practice'?demonstration():emptyState(),version:row?.version||0,exists:!!row};}
async function role(userId:string|undefined){if(!userId)return null;return (await config.DB.prepare('SELECT role FROM operators WHERE user_id=?').bind(userId).first<{role:string}>())?.role||null;}
function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||![new URL(req.url).origin,config.PUBLIC_ORIGIN].includes(origin))throw Error('同じサイトの画面から操作してください');}
export async function GET(req:Request){try{const user=await getChatGPTUser(),r=await read(eventId(req)),operator=await role(user?.userId),count=await config.DB.prepare('SELECT COUNT(*) AS n FROM operators').first<{n:number}>();const body={...publicView(r.state),version:r.version,event:eventId(req),operator:!!operator,role:operator,signedIn:!!user,userId:user?.userId||null,canClaim:!!user&&count?.n===0&&config.ALLOW_OWNER_BOOTSTRAP==='true',...(operator?{raw:r.state,calculated:calculate(r.state)}:{})};return response(body);}catch(e){return response({error:(e as Error).message},503);}}
export async function POST(req:Request){try{sameOrigin(req);const user=await getChatGPTUser();if(!user)return response({error:'運営アカウントでサインインしてください'},401);const data:any=await req.json();if(data.command==='claim'){const count=await config.DB.prepare('SELECT COUNT(*) AS n FROM operators').first<{n:number}>();if(count?.n||config.ALLOW_OWNER_BOOTSTRAP!=='true')return response({error:'管理者の初期登録を受け付けていません'},403);await config.DB.prepare("INSERT INTO operators(user_id,role,created_at) SELECT ?,'owner',? WHERE NOT EXISTS(SELECT 1 FROM operators)").bind(user.userId,new Date().toISOString()).run();return response({ok:!!await role(user.userId)});}
 const operator=await role(user.userId);if(!operator)return response({error:'運営の権限がありません'},403);
 if(data.command==='grant'){if(operator!=='owner')return response({error:'管理者のみ追加できます'},403);if(typeof data.userId!=='string'||!/^[-\w:]{4,160}$/.test(data.userId))throw Error('スタッフのユーザーIDが不正です');await config.DB.prepare("INSERT INTO operators(user_id,role,created_at) VALUES(?,'editor',?) ON CONFLICT(user_id) DO NOTHING").bind(data.userId,new Date().toISOString()).run();return response({ok:true});}
 const id=eventId(req),r=await read(id);if(!Number.isInteger(data.version)||data.version!==r.version)return response({error:'別の担当者が更新しました。最新の画面を確認してください'},409);
 let next=r.state;
 if(data.command==='action'){if(next.actions.length>=800)throw Error('操作数の上限です。台帳を書き出して確認してください');next=append(r.state,{...data.action,operator:user.userId,recordedAt:new Date().toISOString()});const a=next.actions.at(-1),draft=draftFor(a,next);if(draft)next={...next,news:[...next.news,{...draft,private:!!draft.private,id:'news-'+a.id,published:false,time:a.time,sourceId:a.id}]};if(['void','replace','adjust'].includes(a.kind))next={...next,news:[...next.news,{id:'news-'+a.id,headline:'運営から記録訂正のお知らせ',body:a.reason,private:false,target:'all',published:false,time:a.time,sourceId:a.id}]};}
 else if(data.command==='news'){const n=r.state.news.find((n:any)=>n.id===data.id);if(!n)throw Error('記事が見つかりません');if(typeof data.headline!=='string'||data.headline.length<1||data.headline.length>100||typeof data.body!=='string'||data.body.length>3000)throw Error('見出しは100字、本文は3000字以内です');if(data.published&&n.private)throw Error('チーム限定の掲載予告は全体公開できません。本文をコピーして該当チームLINEへ送ってください');next={...r.state,news:r.state.news.map((n:any)=>n.id===data.id?{...n,headline:data.headline,body:data.body,published:!!data.published,reviewedBy:user.userId}:n)};}
 else if(data.command==='teams'){if(!Array.isArray(data.teams)||data.teams.length!==6)throw Error('6チームを指定してください');next={...r.state,teams:r.state.teams.map((t:any,i:number)=>{const n=data.teams[i];if(n.id!==t.id||typeof n.name!=='string'||!n.name.trim()||n.name.length>30||!/^#[\da-f]{6}$/i.test(n.color))throw Error('グループ名・色が不正です');return {...t,name:n.name.trim(),color:n.color};})};}
 else if(data.command==='import'){if(operator!=='owner')return response({error:'復元は管理者のみできます'},403);const raw=data.state;if(!raw||!Array.isArray(raw.actions)||raw.actions.length>800||!Array.isArray(raw.teams)||raw.teams.length!==6||!Array.isArray(raw.news)||raw.news.length>1600||raw.teams.some((t:any,i:number)=>t.id!==`G${i+1}`||t.initialGb!==600||typeof t.name!=='string'||!t.name.trim()||t.name.length>30||!/^#[\da-f]{6}$/i.test(t.color))||raw.news.some((n:any)=>typeof n.id!=='string'||typeof n.headline!=='string'||n.headline.length>100||typeof n.body!=='string'||n.body.length>3000||(n.private!==undefined&&typeof n.private!=='boolean')||typeof n.published!=='boolean'||(n.private&&n.published)))throw Error('バックアップの形式が不正です');calculate(raw);next=raw;}
 else throw Error('操作が不正です');
 if(!r.exists)await config.DB.prepare('INSERT INTO event_store(id,payload,version,updated_at) VALUES(?,?,0,?) ON CONFLICT(id) DO NOTHING').bind(id,JSON.stringify(r.state),new Date().toISOString()).run();
 const result=await config.DB.prepare('UPDATE event_store SET payload=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(JSON.stringify(next),new Date().toISOString(),id,r.version).run();if(result.meta.changes!==1)return response({error:'同時更新がありました。最新の画面を確認してください'},409);return response({ok:true,version:r.version+1});
 }catch(e){return response({error:(e as Error).message},400);}}
