'use client';
import { useEffect,useState,useRef } from 'react';
import NewsDesk from './admin/news-desk';
import { portalHref } from '../lib/articles.mjs';
import { rules } from '../lib/core.mjs';
type Any = any;
const phases:Record<string,string>={preparing:'準備中',tour:'全国ツアー',closed:'取引終了・出順選択',live:'武道館ライブ',announced:'結果公開'};
const labels:Record<string,string>={stage:'ツアー採点',mission:'ミッション報酬',purchase:'GBで購入',sns:'SNS評価',scandal_open:'スキャンダル予告',scandal_resolve:'スキャンダル対応',collab:'2組の合同ロケ',settle:'17時の定期収入',scandal_publish:'スキャンダル結果公開',final:'武道館採点',adjust:'記録の訂正'};
const man=(n:number)=>(n/10000).toLocaleString('ja-JP',{maximumFractionDigits:1})+'万人';
export default function Dashboard(){
 const [snapshot,setSnapshot]=useState<Any>(null),[err,setErr]=useState(''),[notice,setNotice]=useState(''),[event,setEvent]=useState('practice'),[tab,setTab]=useState('admin'),[busy,setBusy]=useState(false),[kind,setKind]=useState('stage'),[team,setTeam]=useState('G1'),[venue,setVenue]=useState('A'),[item,setItem]=useState('work1'),[product,setProduct]=useState('ad'),[proof,setProof]=useState(''),[score,setScore]=useState<number[]>([0,0,0,0]),[judges,setJudges]=useState<number[][]>(Array.from({length:3},()=>[0,0,0,0,0])),[resolution,setResolution]=useState('cover'),[partner,setPartner]=useState('G2'),[postType,setPostType]=useState('idol'),[clock,setClock]=useState('15:30'),[receiptTime,setReceiptTime]=useState(''),[reason,setReason]=useState(''),[gb,setGb]=useState(0),[fans,setFans]=useState(0),[staffId,setStaffId]=useState('');
 const requestSerial=useRef(0),currentEvent=useRef(event);currentEvent.current=event;
 const load=async()=>{const requestedEvent=event,serial=++requestSerial.current;try{const r=await fetch('/api/admin/event?event='+event,{cache:'no-store'}),data:Any=await r.json();if(!r.ok)throw Error(data.error);if(requestedEvent===currentEvent.current&&serial===requestSerial.current){setSnapshot(data);setErr('');}}catch(e){if(requestedEvent===currentEvent.current&&serial===requestSerial.current)setErr((e as Error).message);}};
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer);},[event]);
 async function send(body:Any){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/event?event='+event,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:snapshot?.version,...body})}),d:Any=await r.json();if(!r.ok)throw Error(d.error);setNotice('記録しました');await load();return true;}catch(e){setNotice((e as Error).message);await load();return false;}finally{setBusy(false);}}
 function action(){let a:Any={id:crypto.randomUUID(),kind,teamId:team,time:receiptTime||snapshot.clock,proof};if(kind==='stage')Object.assign(a,{venue,scores:score});if(kind==='mission')a.missionId=item;if(kind==='purchase')a.productId=product;if(kind==='sns')Object.assign(a,{postType,venue});if(kind==='scandal_resolve')a.resolution=resolution;if(kind==='collab'){delete a.teamId;a.teamIds=[team,partner];}if(kind==='final')a.judges=judges;if(kind==='adjust')Object.assign(a,{gb,fans,reason});if(['stage','final'].includes(kind)){const exists=snapshot.calculated.effects.filter((e:Any)=>e.kind===kind&&e.teamId===team).findLast((e:Any)=>kind==='final'||snapshot.raw.actions.find((x:Any)=>x.id===e.id)?.venue===venue||snapshot.raw.actions.find((x:Any)=>x.id===e.id)?.replacement?.venue===venue);if(exists){if(proof.trim().length<4){setNotice('採点済みです。確認内容欄に訂正理由を4文字以上入力してください');return;}a={id:crypto.randomUUID(),kind:'replace',targetId:exists.id,replacement:a,reason:proof,time:snapshot.clock};}}send({command:'action',action:a});}
 function download(value:Any,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
 const byId=(id:string)=>snapshot?.teams.find((t:Any)=>t.id===id)?.name||id;
 const tabs=[['admin','採点・報酬'],['news','記事の編集'],['history','台帳・設定']];
 return <main className="ops-site">
 <header className="masthead"><div className="brand">KEITEKI <strong>CONTROL</strong><span>運営専用 / アイドル駅伝</span></div><div className="header-right"><label>操作するイベント<select disabled={busy} value={event} onChange={e=>{setEvent(e.target.value);setSnapshot(null);}}><option value="practice">練習データ</option><option value="rehearsal">リハーサル</option><option value="production">本番</option></select></label><a href={portalHref(event)} target="_blank" rel="noreferrer">参加者画面 ↗</a></div></header>
 <div className="draft-note">{event==='production'?'本番台帳を操作しています。':'練習・リハーサルです。本番の成績には影響しません。'} 記事の公開には編集画面での確認が必要です。</div>
 <nav aria-label="運営の操作">{tabs.map(([id,title])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{title}</button>)}</nav>
 {err&&<div className="error" role="alert">{err}<button onClick={load}>再読込</button></div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {!snapshot&&!err?<div className="loading">運営の記録を読み込んでいます…</div>:snapshot&&<>
 {snapshot.operator&&<div className="ops-summary"><span>{phases[snapshot.phase]} / {snapshot.clock}</span>{snapshot.teams.map((t:Any)=><span key={t.id}>{t.name}: {man(t.totalFans)} / {t.gb}GB</span>)}</div>}
 {tab==='news'&&snapshot.operator&&<NewsDesk snapshot={snapshot} event={event} reload={load}/>}
 {tab==='admin'&&snapshot.operator&&<section className="content"><h2>運営入力</h2><div className="control-bar"><label>イベント時刻<input type="time" value={clock} onChange={e=>setClock(e.target.value)}/></label><button disabled={busy} onClick={()=>send({command:'action',action:{id:crypto.randomUUID(),kind:'clock',value:clock}})}>時刻を更新</button><label>進行<select value={snapshot.phase} onChange={e=>send({command:'action',action:{id:crypto.randomUUID(),kind:'phase',value:e.target.value}})} disabled={busy}>{Object.entries(phases).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></label></div><div className="admin-grid"><form onSubmit={e=>{e.preventDefault();action();}}><label>操作<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></label>{!['settle','scandal_publish'].includes(kind)&&<label>グループ<select value={team} onChange={e=>setTeam(e.target.value)}>{snapshot.teams.map((t:Any)=><option key={t.id} value={t.id}>{t.id} {t.name}</option>)}</select></label>}
 {['stage','sns'].includes(kind)&&<label>会場<select value={venue} onChange={e=>{setVenue(e.target.value);setScore([3,3,3,5]);}}>{rules.venues.map(v=><option key={v.id} value={v.id}>{v.id} {v.theme}</option>)}</select></label>}
 {kind==='stage'&&<div className="scores">{rules.venues.find(v=>v.id===venue)?.criteria.map((label,i)=><label key={i}>{label}<input type="number" min="0" max={rules.venues.find(v=>v.id===venue)?.maxima[i]} value={score[i]} onChange={e=>setScore(score.map((s,j)=>i===j?Number(e.target.value):s))}/></label>)}</div>}
 {kind==='mission'&&<label>ミッション<select value={item} onChange={e=>setItem(e.target.value)}>{rules.missions.map(m=><option key={m.id} value={m.id}>{m.name} / {m.gb}GB</option>)}</select></label>}
 {kind==='purchase'&&<label>購入するもの<select value={product} onChange={e=>setProduct(e.target.value)}>{rules.products.map(p=><option key={p.id} value={p.id}>{p.name} / {p.price}GB</option>)}</select></label>}
 {kind==='sns'&&<label>投稿者<select value={postType} onChange={e=>setPostType(e.target.value)}><option value="idol">アイドルの投稿</option><option value="fan">古参ファンのライブ報告</option></select></label>}
 {kind==='scandal_resolve'&&<label>対応結果<select value={resolution} onChange={e=>setResolution(e.target.value)}><option value="cover">もみ消し / 200GB</option><option value="apology">釈明成功 / ＋2万人</option><option value="publicity">話題化成功 / ＋3万人</option><option value="failed">対応失敗 / −3万人</option></select></label>}
 {kind==='collab'&&<label>共演するグループ<select value={partner} onChange={e=>setPartner(e.target.value)}>{snapshot.teams.map((t:Any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 {kind==='final'&&<div className="final-scores">{judges.map((j,idx)=><fieldset key={idx}><legend>審査員{idx+1}</legend>{rules.final.criteria.map((label,i)=><label key={i}>{label}<input type="number" min="0" max={rules.final.maxima[i]} value={j[i]} onChange={e=>setJudges(judges.map((row,k)=>idx===k?row.map((n,p)=>p===i?Number(e.target.value):n):row))}/></label>)}</fieldset>)}</div>}
 {kind==='adjust'&&<><label>GBの増減<input type="number" value={gb} onChange={e=>setGb(Number(e.target.value))}/></label><label>ファン数の増減（人）<input type="number" value={fans} onChange={e=>setFans(Number(e.target.value))}/></label><label>訂正理由<input value={reason} onChange={e=>setReason(e.target.value)} minLength={4} required/></label></>}
 <label>実施・受付時刻（遅延入力時のみ）<input type="time" value={receiptTime} onChange={e=>setReceiptTime(e.target.value)}/></label><label>確認内容・投稿内容<textarea value={proof} onChange={e=>setProof(e.target.value)} placeholder="確認した活動や提出動画の内容を記録"/></label><button className="primary" disabled={busy}>{busy?'保存中…':'確認して登録'}</button><p className="footnote">重複受取・残高不足・回数上限・締切は登録時に確認します。ニュースは下書きから確認して公開してください。</p></form><aside><h3>入力後の確認</h3><p>台帳に記録すると、活動に応じてニュースの下書きを作成します。</p><p>記事の要約・本文・架空コメントを「記事の編集」で確認してから、全体公開またはチーム用リンクを発行してください。</p><button onClick={()=>setTab('news')}>記事の編集へ（{snapshot.raw.news.filter((n:Any)=>!n.published&&!n.sharedAt).length}件の下書き）</button><p>チーム別スキャンダル予告 → 対応受付 → 16:50に結果処理 → 6組の記事を確認して公開。</p></aside></div></section>}
 {tab==='history'&&snapshot.operator&&<section className="content"><h2>台帳とバックアップ</h2><button onClick={()=>download(snapshot.raw,`idol-ekiden-${event}-${snapshot.version}.json`)}>台帳をJSONで保存</button><label className="file-label">保存した台帳を復元<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f&&confirm('現在の記録をバックアップの内容で置き換えます。事前にJSON保存してください。')){try{await send({command:'import',state:JSON.parse(await f.text())});}catch{setNotice('JSONの形式を確認してください');}}}}/></label><div className="scroll"><table><thead><tr><th>時刻</th><th>対象</th><th>操作</th><th>GB</th><th>ファン</th><th>訂正</th></tr></thead><tbody>{[...snapshot.calculated.effects].reverse().map((e:Any)=><tr key={e.id}><td>{e.time}</td><td>{e.teamId||e.teamIds?.join('・')||'全体'}</td><td>{e.label}<small>{e.reason}</small></td><td>{e.gb}</td><td>{man(e.fans)}</td><td>{!['phase','clock'].includes(e.kind)&&<button disabled={busy} onClick={()=>{const reason=prompt('取り消す理由を4文字以上で入力');if(reason)send({command:'action',action:{id:crypto.randomUUID(),kind:'void',targetId:e.id,reason}});}}>取消</button>}</td></tr>)}</tbody></table></div><h3>グループ名・色</h3><TeamEditor teams={snapshot.raw.teams} busy={busy} save={(teams:Any)=>send({command:'teams',teams})}/><h3>運営スタッフの権限</h3><p>あなたのユーザーID：<code>{snapshot.userId}</code></p>{snapshot.role==='owner'&&<div className="control-bar"><label>追加するスタッフのユーザーID<input value={staffId} onChange={e=>setStaffId(e.target.value)}/></label><button disabled={busy} onClick={()=>send({command:'grant',userId:staffId})}>運営権限を追加</button></div>}</section>}
 {!snapshot.operator&&<section className="operator-entry">{snapshot.canClaim?<button onClick={()=>send({command:'claim'})}>所有者として運営を開始</button>:snapshot.signedIn?<p>閲覧用アカウントです。スタッフ追加にはユーザーID <code>{snapshot.userId}</code> を管理者へ伝えてください。</p>:<a href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">運営アカウントでサインイン</a>}</section>}
 </>}
 <footer>アイドル駅伝 / 恵迪寮祭 <span>参加者・運営の共通ルールはGitHubで管理</span></footer></main>;
}
function TeamEditor({teams,busy,save}:Any){const [draft,setDraft]=useState(teams);return <form onSubmit={e=>{e.preventDefault();save(draft);}}>{draft.map((t:Any,i:number)=><div className="team-edit" key={t.id}><span>{t.id}</span><input aria-label={t.id+'の名前'} value={t.name} maxLength={30} onChange={e=>setDraft(draft.map((x:Any,j:number)=>i===j?{...x,name:e.target.value}:x))}/><input aria-label={t.id+'の色'} type="color" value={t.color} onChange={e=>setDraft(draft.map((x:Any,j:number)=>i===j?{...x,color:e.target.value}:x))}/></div>)}<button disabled={busy}>名前と色を保存</button></form>;}
