'use client';
import { useEffect,useState,useRef } from 'react';
import { rules } from '../lib/core.mjs';
type Any = any;
const phases:Record<string,string>={preparing:'準備中',tour:'全国ツアー',closed:'取引終了・出順選択',live:'武道館ライブ',announced:'結果公開'};
const labels:Record<string,string>={stage:'ツアー採点',mission:'ミッション報酬',purchase:'GBで購入',sns:'SNS評価',scandal_open:'スキャンダル予告',scandal_resolve:'スキャンダル対応',collab:'2組の合同ロケ',settle:'17時の定期収入',scandal_publish:'スキャンダル結果公開',final:'武道館採点',adjust:'記録の訂正'};
const man=(n:number)=>(n/10000).toLocaleString('ja-JP',{maximumFractionDigits:1})+'万人';
export default function Dashboard(){
 const [snapshot,setSnapshot]=useState<Any>(null),[err,setErr]=useState(''),[notice,setNotice]=useState(''),[event,setEvent]=useState('practice'),[tab,setTab]=useState('ranking'),[busy,setBusy]=useState(false),[kind,setKind]=useState('stage'),[team,setTeam]=useState('G1'),[venue,setVenue]=useState('A'),[item,setItem]=useState('work1'),[product,setProduct]=useState('ad'),[proof,setProof]=useState(''),[score,setScore]=useState<number[]>([0,0,0,0]),[judges,setJudges]=useState<number[][]>(Array.from({length:3},()=>[0,0,0,0,0])),[resolution,setResolution]=useState('cover'),[partner,setPartner]=useState('G2'),[postType,setPostType]=useState('idol'),[clock,setClock]=useState('15:30'),[receiptTime,setReceiptTime]=useState(''),[reason,setReason]=useState(''),[gb,setGb]=useState(0),[fans,setFans]=useState(0),[staffId,setStaffId]=useState('');
 const requestSerial=useRef(0),currentEvent=useRef(event);currentEvent.current=event;
 const load=async()=>{const requestedEvent=event,serial=++requestSerial.current;try{const r=await fetch('/api/event?event='+event,{cache:'no-store'}),data:Any=await r.json();if(!r.ok)throw Error(data.error);if(requestedEvent===currentEvent.current&&serial===requestSerial.current){setSnapshot(data);setErr('');}}catch(e){if(requestedEvent===currentEvent.current&&serial===requestSerial.current)setErr((e as Error).message);}};
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer);},[event]);
 async function send(body:Any){setBusy(true);setNotice('');try{const r=await fetch('/api/event?event='+event,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:snapshot?.version,...body})}),d:Any=await r.json();if(!r.ok)throw Error(d.error);setNotice('記録しました');await load();return true;}catch(e){setNotice((e as Error).message);await load();return false;}finally{setBusy(false);}}
 function action(){let a:Any={id:crypto.randomUUID(),kind,teamId:team,time:receiptTime||snapshot.clock,proof};if(kind==='stage')Object.assign(a,{venue,scores:score});if(kind==='mission')a.missionId=item;if(kind==='purchase')a.productId=product;if(kind==='sns')Object.assign(a,{postType,venue});if(kind==='scandal_resolve')a.resolution=resolution;if(kind==='collab'){delete a.teamId;a.teamIds=[team,partner];}if(kind==='final')a.judges=judges;if(kind==='adjust')Object.assign(a,{gb,fans,reason});if(['stage','final'].includes(kind)){const exists=snapshot.calculated.effects.filter((e:Any)=>e.kind===kind&&e.teamId===team).findLast((e:Any)=>kind==='final'||snapshot.raw.actions.find((x:Any)=>x.id===e.id)?.venue===venue||snapshot.raw.actions.find((x:Any)=>x.id===e.id)?.replacement?.venue===venue);if(exists){if(proof.trim().length<4){setNotice('採点済みです。確認内容欄に訂正理由を4文字以上入力してください');return;}a={id:crypto.randomUUID(),kind:'replace',targetId:exists.id,replacement:a,reason:proof,time:snapshot.clock};}}send({command:'action',action:a});}
 function download(value:Any,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
 const byId=(id:string)=>snapshot?.teams.find((t:Any)=>t.id===id)?.name||id;
 const tabs=[['ranking','ランキング'],['news','芸能ニュース'],['routes','チームの予定'],['rules','ルール・料金'],...(snapshot?.operator?[['admin','運営入力'],['history','台帳・設定']]:[])];
 return <main>
 <header className="masthead"><div className="brand">KEITEKI <strong>RECORDS</strong><span>アイドル駅伝</span></div><div className="header-right"><label>表示するイベント<select aria-label="イベント" disabled={busy} value={event} onChange={e=>{setEvent(e.target.value);setSnapshot(null);}}><option value="practice">練習データ</option><option value="rehearsal">リハーサル</option><option value="production">本番</option></select></label><a href="https://github.com/bikyousitsu/idol-ekiden" target="_blank" rel="noreferrer">企画資料 ↗</a></div></header>
 <section className="hero"><div><p className="eyebrow">寮から、メジャーデビューへ</p><h1>推しの成長を、<br/>みんなで見届ける。</h1><p>6グループのファン数とGBを公開。<br className="mobile"/>最後は17:30、共用棟の武道館ライブへ。</p></div><div className="live-status"><span className="live-dot"/>{snapshot?phases[snapshot.phase]:'読み込み中'}<strong>{snapshot?.clock||'—:—'}</strong><small>運営が進めるイベント時刻</small></div></section>
 <div className="draft-note">ルール・料金は試運転用の仮案です。{event==='practice'?'この画面の結果は練習データです。':event==='rehearsal'?'リハーサルの記録です。':'本番用の記録を表示しています。'} 開催日と会場間の徒歩時間は未確定。</div>
 <nav aria-label="表示内容">{tabs.map(([id,title])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{title}</button>)}</nav>
 {err&&<div className="error" role="alert">接続できません：{err}<button onClick={load}>再読込</button></div>}
 {notice&&<div className="notice" role="status">{notice}</div>}
 {!snapshot&&!err?<div className="loading">記録を読み込んでいます…</div>:snapshot&&<>
 {tab==='ranking'&&<section className="content"><div className="section-heading"><h2>グループランキング</h2><span>{snapshot.phase==='live'?'武道館の得点は全組終了後に公開':'ファン数で順位を決定'} / 自動更新5秒</span></div><div className="ranking-table"><div className="ranking-head"><span>順位</span><span>グループ</span><span>獲得ファン</span><span>GB残高</span><span>ツアー</span></div>{snapshot.teams.map((t:Any)=><article key={t.id} className={'rank-row '+(t.rank===1?'leader':'')} style={{'--team-color':t.color} as Any}><span className="rank">{String(t.rank).padStart(2,'0')}</span><div className="team-name"><span className="team-color"/>{t.name}<small>{t.id}</small></div><strong className="fans">{man(t.totalFans)}</strong><strong className="balance">{t.gb.toLocaleString()} <small>GB</small></strong><span className="progress">{Object.keys(t.stages).length}/4<small>会場終了</small></span></article>)}</div><p className="footnote">途中順位は会場を回った数にも影響します。武道館は60点満点、1点につき新規ファン1万人。</p><div className="latest"><h3>最新の芸能ニュース</h3>{snapshot.news.length? <><strong>{snapshot.news.at(-1).headline}</strong><p>{snapshot.news.at(-1).body}</p></>:<p>運営が確認したニュースをここに掲載します。</p>}</div></section>}
 {tab==='news'&&<section className="content news-list"><div className="section-heading"><h2>週刊ケイテキ</h2><span>運営が確認した活動を掲載</span></div>{[...snapshot.news].reverse().map((n:Any)=><article key={n.id}><span className="news-time">{n.time}</span><h3>{n.headline}</h3><p>{n.body}</p><button onClick={()=>navigator.clipboard.writeText(n.headline+'\n'+n.body).then(()=>setNotice('本文をコピーしました')).catch(()=>setNotice('コピーできません。本文を選択してコピーしてください'))}>本文をコピー</button></article>)}{!snapshot.news.length&&<p>公開済みの記事はまだありません。</p>}</section>}
 {tab==='routes'&&<section className="content"><div className="section-heading"><h2>6グループの行動予定</h2><span>会場の受入は各枠1組</span></div><div className="scroll"><table><thead><tr><th>時刻</th>{rules.teams.map(t=><th key={t.id}>{byId(t.id)}</th>)}</tr></thead><tbody>{Array.from({length:6},(_,i)=>{const time=15*60+30+i*15;return <tr key={i}><th>{String(Math.floor(time/60)).padStart(2,'0')}:{String(time%60).padStart(2,'0')}</th>{rules.routes.map((r,j)=><td key={j}>{r[i]==='FREE'?'移動・自由活動':rules.venues.find(v=>v.id===r[i])?.theme}</td>)}</tr>;})}</tbody></table></div><div className="plain-list"><p>15:00 記者会見 ／ 15:30 ツアー開始 ／ 17:00 お題概要発表</p><p>17:10 お題申請締切 ／ 17:20 共用棟に全員集合・取引締切 ／ 17:30 武道館ライブ</p><p>自由枠は移動を優先。合同ロケは各組1回、会えない場合は動画リレーで代替。</p></div></section>}
 {tab==='rules'&&<section className="content"><h2>お金を稼ぎ、推しの活動に使う</h2><p>初期600GB。ステージの点数×1万人でファン増加。アイドルと古参ファンは一緒に行動します。</p><div className="two-columns"><div><h3>稼ぐ</h3><table><thead><tr><th>ミッション</th><th>報酬</th></tr></thead><tbody>{rules.missions.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.gb}GB{m.fans>0?' ＋'+man(m.fans):''}</td></tr>)}</tbody></table></div><div><h3>使う</h3><table><thead><tr><th>購入</th><th>料金・上限</th></tr></thead><tbody>{rules.products.map(p=><tr key={p.id}><td>{p.name}{p.fans>0?<small> ＋{man(p.fans)}</small>:null}</td><td>{p.price}GB / {p.max}回</td></tr>)}</tbody></table></div></div><h3>スキャンダルは全グループ1回</h3><p>16:00予告、16:45対応締切、16:50結果公開。もみ消し200GB、釈明成功＋2万人、話題化成功＋3万人、失敗・未対応−3万人（ファン数の下限0人）。</p><h3>定期収入は17:00に1回</h3><p>スポンサー契約済みなら200GB。ファンクラブ開設済みならファン10万人ごと50GB、上限300GB。SNSは承認1件＋1万人、全投稿を合算して1グループ最大4万人。</p><h3>勝利条件</h3><p>武道館の3人の審査点を平均し、合計60点に換算。全組の披露後にファンへ反映します。同ファン数なら武道館点、さらに同点なら「全アイドルが輝いているか」、なお同点なら同時デビュー。</p></section>}
 {tab==='admin'&&snapshot.operator&&<section className="content"><h2>運営入力</h2><div className="control-bar"><label>イベント時刻<input type="time" value={clock} onChange={e=>setClock(e.target.value)}/></label><button disabled={busy} onClick={()=>send({command:'action',action:{id:crypto.randomUUID(),kind:'clock',value:clock}})}>時刻を更新</button><label>進行<select value={snapshot.phase} onChange={e=>send({command:'action',action:{id:crypto.randomUUID(),kind:'phase',value:e.target.value}})} disabled={busy}>{Object.entries(phases).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></label></div><div className="admin-grid"><form onSubmit={e=>{e.preventDefault();action();}}><label>操作<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></label>{!['settle','scandal_publish'].includes(kind)&&<label>グループ<select value={team} onChange={e=>setTeam(e.target.value)}>{snapshot.teams.map((t:Any)=><option key={t.id} value={t.id}>{t.id} {t.name}</option>)}</select></label>}
 {['stage','sns'].includes(kind)&&<label>会場<select value={venue} onChange={e=>{setVenue(e.target.value);setScore([3,3,3,5]);}}>{rules.venues.map(v=><option key={v.id} value={v.id}>{v.id} {v.theme}</option>)}</select></label>}
 {kind==='stage'&&<div className="scores">{rules.venues.find(v=>v.id===venue)?.criteria.map((label,i)=><label key={i}>{label}<input type="number" min="0" max={rules.venues.find(v=>v.id===venue)?.maxima[i]} value={score[i]} onChange={e=>setScore(score.map((s,j)=>i===j?Number(e.target.value):s))}/></label>)}</div>}
 {kind==='mission'&&<label>ミッション<select value={item} onChange={e=>setItem(e.target.value)}>{rules.missions.map(m=><option key={m.id} value={m.id}>{m.name} / {m.gb}GB</option>)}</select></label>}
 {kind==='purchase'&&<label>購入するもの<select value={product} onChange={e=>setProduct(e.target.value)}>{rules.products.map(p=><option key={p.id} value={p.id}>{p.name} / {p.price}GB</option>)}</select></label>}
 {kind==='sns'&&<label>投稿者<select value={postType} onChange={e=>setPostType(e.target.value)}><option value="idol">アイドルの投稿</option><option value="fan">古参ファンのライブ報告</option></select></label>}
 {kind==='scandal_resolve'&&<label>対応結果<select value={resolution} onChange={e=>setResolution(e.target.value)}><option value="cover">もみ消し / 200GB</option><option value="apology">釈明成功 / ＋2万人</option><option value="publicity">話題化成功 / ＋3万人</option><option value="failed">対応失敗 / −3万人</option></select></label>}
 {kind==='collab'&&<label>共演するグループ<select value={partner} onChange={e=>setPartner(e.target.value)}>{snapshot.teams.map((t:Any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 {kind==='final'&&<div className="final-scores">{judges.map((j,idx)=><fieldset key={idx}><legend>審査員{idx+1}</legend>{rules.final.criteria.map((label,i)=><label key={i}>{label}<input type="number" min="0" max={rules.final.maxima[i]} value={j[i]} onChange={e=>setJudges(judges.map((row,k)=>idx===k?row.map((n,p)=>p===i?Number(e.target.value):n):row))}/></label>)}</fieldset>)}</div>}
 {kind==='adjust'&&<><label>GBの増減<input type="number" value={gb} onChange={e=>setGb(Number(e.target.value))}/></label><label>ファン数の増減（人）<input type="number" value={fans} onChange={e=>setFans(Number(e.target.value))}/></label><label>訂正理由<input value={reason} onChange={e=>setReason(e.target.value)} minLength={4} required/></label></>}
 <label>実施・受付時刻（遅延入力時のみ）<input type="time" value={receiptTime} onChange={e=>setReceiptTime(e.target.value)}/></label><label>確認内容・投稿内容<textarea value={proof} onChange={e=>setProof(e.target.value)} placeholder="確認した活動や提出動画の内容を記録"/></label><button className="primary" disabled={busy}>{busy?'保存中…':'確認して登録'}</button><p className="footnote">重複受取・残高不足・回数上限・締切は登録時に確認します。ニュースは下書きから確認して公開してください。</p></form><aside><h3>ニュースの下書き</h3>{snapshot.raw.news.filter((n:Any)=>!n.published).map((n:Any)=><NewsEditor key={n.id} news={n} busy={busy} save={(b:Any)=>send(b)} notify={setNotice}/>)}{!snapshot.raw.news.some((n:Any)=>!n.published)&&<p>操作に応じて下書きを作ります。</p>}</aside></div></section>}
 {tab==='history'&&snapshot.operator&&<section className="content"><h2>台帳とバックアップ</h2><button onClick={()=>download(snapshot.raw,`idol-ekiden-${event}-${snapshot.version}.json`)}>台帳をJSONで保存</button><label className="file-label">保存した台帳を復元<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f&&confirm('現在の記録をバックアップの内容で置き換えます。事前にJSON保存してください。')){try{await send({command:'import',state:JSON.parse(await f.text())});}catch{setNotice('JSONの形式を確認してください');}}}}/></label><div className="scroll"><table><thead><tr><th>時刻</th><th>対象</th><th>操作</th><th>GB</th><th>ファン</th><th>訂正</th></tr></thead><tbody>{[...snapshot.calculated.effects].reverse().map((e:Any)=><tr key={e.id}><td>{e.time}</td><td>{e.teamId||e.teamIds?.join('・')||'全体'}</td><td>{e.label}<small>{e.reason}</small></td><td>{e.gb}</td><td>{man(e.fans)}</td><td>{!['phase','clock'].includes(e.kind)&&<button disabled={busy} onClick={()=>{const reason=prompt('取り消す理由を4文字以上で入力');if(reason)send({command:'action',action:{id:crypto.randomUUID(),kind:'void',targetId:e.id,reason}});}}>取消</button>}</td></tr>)}</tbody></table></div><h3>グループ名・色</h3><TeamEditor teams={snapshot.raw.teams} busy={busy} save={(teams:Any)=>send({command:'teams',teams})}/><h3>運営スタッフの権限</h3><p>あなたのユーザーID：<code>{snapshot.userId}</code></p>{snapshot.role==='owner'&&<div className="control-bar"><label>追加するスタッフのユーザーID<input value={staffId} onChange={e=>setStaffId(e.target.value)}/></label><button disabled={busy} onClick={()=>send({command:'grant',userId:staffId})}>運営権限を追加</button></div>}</section>}
 {!snapshot.operator&&<section className="operator-entry">{snapshot.canClaim?<button onClick={()=>send({command:'claim'})}>この非公開サイトの管理者として運営を開始</button>:snapshot.signedIn?<p>閲覧用アカウントです。スタッフ追加にはユーザーID <code>{snapshot.userId}</code> を管理者へ伝えてください。</p>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top">運営アカウントでサインイン</a>}</section>}
 </>}
 <footer>アイドル駅伝 / 恵迪寮祭 <span>参加者・運営の共通ルールはGitHubで管理</span></footer></main>;
}
function NewsEditor({news,busy,save,notify}:Any){const [headline,setHeadline]=useState(news.headline),[body,setBody]=useState(news.body);return <article className="news-editor"><small>{news.private?`${news.target}限定・全体公開しない`:'全体公開用'} / {news.time}</small><label>見出し<input value={headline} maxLength={100} onChange={e=>setHeadline(e.target.value)}/></label><label>本文<textarea value={body} maxLength={3000} onChange={e=>setBody(e.target.value)}/></label><div className="button-row"><button disabled={busy} onClick={()=>save({command:'news',id:news.id,headline,body,published:false})}>下書きを保存</button>{!news.private&&<button disabled={busy} className="primary" onClick={()=>save({command:'news',id:news.id,headline,body,published:true})}>確認して公開</button>}<button onClick={()=>navigator.clipboard.writeText(headline+'\n'+body).then(()=>notify(news.private?'該当チームLINE用の本文をコピーしました':'LINE用の本文をコピーしました')).catch(()=>notify('本文を選択してコピーしてください'))}>LINE用にコピー</button></div></article>;}
function TeamEditor({teams,busy,save}:Any){const [draft,setDraft]=useState(teams);return <form onSubmit={e=>{e.preventDefault();save(draft);}}>{draft.map((t:Any,i:number)=><div className="team-edit" key={t.id}><span>{t.id}</span><input aria-label={t.id+'の名前'} value={t.name} maxLength={30} onChange={e=>setDraft(draft.map((x:Any,j:number)=>i===j?{...x,name:e.target.value}:x))}/><input aria-label={t.id+'の色'} type="color" value={t.color} onChange={e=>setDraft(draft.map((x:Any,j:number)=>i===j?{...x,color:e.target.value}:x))}/></div>)}<button disabled={busy}>名前と色を保存</button></form>;}
