'use client';
import { useState } from 'react';
import { portalHref,articleHref } from '../lib/articles.mjs';
export const man=(n:number)=>(n/10000).toLocaleString('ja-JP',{maximumFractionDigits:1})+'万人';
export function NewsHeader({event='production',section='ニュース'}:{event?:string,section?:string}){const base=portalHref(event);return <><div className="news-topline">恵迪寮祭 アイドル駅伝 <span>参加者向け・公開情報</span></div><header className="news-masthead"><a href={base} aria-label="ケイテキニュース トップ"><span className="news-logo">ケイテキ!</span><strong>ニュース</strong></a><p>6組の成長を、現場から。</p></header><nav className="news-nav" aria-label="参加者メニュー">{[['ニュース',''],['ファン数・GB','#ranking'],['チームの予定','#routes'],['ルール','#rules']].map(([s,hash])=><a key={s} className={s===section?'current':''} href={base+hash}>{s}</a>)}<a href="https://github.com/bikyousitsu/idol-ekiden" target="_blank" rel="noreferrer">企画資料 ↗</a></nav>{event!=='production'&&<div className="demo-banner">練習用の表示です。記事・コメント・成績は本番の結果ではありません。</div>}</>;}
export function Artwork({theme='stage',small=false}:{theme?:string,small?:boolean}){const themes:any={stage:['#0e2d66','#c444ff','全国ツアー','KEITEKI LIVE'],scandal:['#233443','#db314d','編集部から','WEEKLY KEITEKI'],collab:['#006859','#e6ba31','ライバルと、共演。','COLLAB LOCATION'],award:['#42133f','#d8b652','寮から、メジャーへ。','KEITEKI RECORDS'],notice:['#0c4c86','#52bddb','現場の最新情報','NEWS DESK']};const [bg,accent,title,sub]=themes[theme]||themes.stage;return <div className={'news-art '+(small?'small':'')} style={{background:bg,'--art-accent':accent} as any} role="img" aria-label={title+'の架空イラスト'}><div className="art-beam beam-one"/><div className="art-beam beam-two"/><span className="art-label">{sub}</span><div className="art-stars">✦ <span>✧</span> ✦</div><strong>{title}</strong><div className="art-stage"><i/><i/><i/><i/><i/><i/></div><small>アイドル駅伝 / 演出用イラスト</small></div>;}
export function Rankings({teams,compact=false}:any){return <div className={'news-ranking '+(compact?'compact':'')}><div className="rank-labels"><span>グループ</span><span>ファン / GB</span></div>{teams.map((t:any)=><div className="news-rank" key={t.id}><b className={t.rank===1?'first':''}>{t.rank}</b><span className="group-chip" style={{borderColor:t.color}}>{t.name}<small>{Object.keys(t.stages).length}/4 会場</small></span><strong>{man(t.totalFans)}<small>{t.gb.toLocaleString()} GB</small></strong></div>)}</div>;}
export function Comments({comments}:any){const [sort,setSort]=useState('recommended');let list=[...comments];if(sort==='recommended')list.sort((a:any,b:any)=>b.agree-a.agree);if(sort==='spicy')list=list.filter((c:any)=>c.stance==='辛口');return <section className="fiction-comments"><h2>みんなのコメント <span>{comments.length}件</span></h2><p className="fiction-disclosure">コメント・表示名・反応数はすべて架空の演出です。実際の投稿・投票ではありません。</p><div className="comment-tabs">{[['recommended','おすすめ順'],['original','掲載順'],['spicy','辛口ツッコミ']].map(([s,l])=><button key={s} className={sort===s?'active':''} onClick={()=>setSort(s)}>{l}</button>)}</div>{list.map((c:any)=><article key={c.id} className="fiction-comment"><div><span className="comment-avatar">{c.author.slice(0,1)}</span><b>{c.author}</b><small className={'stance '+(c.stance==='辛口'?'spicy':'')}>{c.stance}</small></div><p>{c.text}</p><footer><span>そう思う {c.agree}</span><span>そう思わない {c.disagree}</span><small>架空の反応数</small></footer></article>)}{!list.length&&<p>この種類のコメントは掲載していません。</p>}</section>;}
export function ArticleReader({article:n,event='production',preview=false,related=[]}:any){const [message,setMessage]=useState('');return <main className="news-site"><NewsHeader event={event}/><div className="news-shell article-shell"><article className="news-article"><div className="breadcrumbs"><a href={portalHref(event)}>トップ</a> › {n.category}</div>{preview&&<div className="demo-banner">運営用プレビュー / 保存済み原稿。公開前の記事は参加者から読めません。</div>}{n.audience==='team'&&<div className="team-banner">{n.teamIds.join('・')} 限定の掲載予告。対象チーム内で確認し、全体LINEへ転送しないでください。</div>}<span className="news-category">{n.category}</span><h1>{n.headline}</h1><div className="article-byline"><span>{n.time} 配信 / 週刊ケイテキ編集部</span><a href="#comments">コメント {n.comments.length}</a></div><p className="article-summary">{n.summary}</p><Artwork theme={n.illustration}/><p className="art-caption">寮祭のゲーム内における演出用イラスト</p><div className="article-prose">{n.body.split(/\n\s*\n/).map((p:string,i:number)=><p key={i}>{p}</p>)}</div><div className="fiction-disclosure">この記事はアイドル駅伝の架空ニュースです。実在の報道ではありません。コメント・反応数は得点に影響しません。</div><div className="article-share"><button onClick={()=>navigator.clipboard.writeText(location.href).then(()=>setMessage('記事URLをコピーしました')).catch(()=>setMessage('アドレス欄からURLをコピーしてください'))}>記事URLをコピー</button><span role="status">{message}</span></div><div id="comments"><Comments comments={n.comments}/></div>{n.audience!=='team'&&related.length>0&&<section className="related"><h2>関連記事</h2>{related.map((r:any)=><a key={r.id} href={articleHref(r,event)}>{r.headline} →</a>)}</section>}</article><aside className="news-aside"><div className="live-card"><small>KEITEKI SPECIAL LIVE</small><strong>17:30</strong><h3>最後の舞台は、武道館。</h3><p>恵迪寮 共用棟<br/>17:20までに全員集合</p></div><div className="aside-box"><h3>ニュースの読み方</h3><p>活動の結果は運営が確認して掲載。順位とGBの最新値はトップのダッシュボードで確認できます。</p><a href={portalHref(event)+'#ranking'}>ファン数・GBを見る →</a></div></aside></div><NewsFooter/></main>;}
export function NewsFooter(){return <footer className="news-footer"><strong>ケイテキ!ニュース</strong><span>恵迪寮祭 アイドル駅伝 / 週刊ケイテキ編集部</span><span>記事・コメントはイベントの架空演出です。</span></footer>;}
