'use client';
import { useEffect,useState } from 'react';
import { rules } from '../lib/core.mjs';
import { portalHref,articleHref,categories } from '../lib/articles.mjs';
import { NewsHeader,NewsFooter,Artwork,Rankings,man } from './news-components';
const phases:any={preparing:'開演前',tour:'全国ツアー',closed:'ライブ準備',live:'武道館ライブ',announced:'結果発表'};
export default function Portal({event='production'}:{event?:string}){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[section,setSection]=useState('ニュース'),[category,setCategory]=useState('すべて'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[team,setTeam]=useState('G1');
 const sections:any={ranking:'ファン数・GB',routes:'チームの予定',rules:'ルール'};
 useEffect(()=>{function hash(){setSection(sections[location.hash.slice(1)]||'ニュース');}hash();window.addEventListener('hashchange',hash);async function load(){try{const r=await fetch('/api/event?event='+event,{cache:'no-store'});if(!r.ok)throw Error('情報を読み込めませんでした');setData(await r.json());setError('');}catch(e){setError((e as Error).message);}}load();const timer=setInterval(load,5000);return()=>{clearInterval(timer);window.removeEventListener('hashchange',hash);};},[event]);
 const news=data?[...data.news].reverse().filter((n:any)=>(category==='すべて'||n.category===category)&&(!search||(n.headline+n.summary+n.body).includes(search))):[];const featured=news[0];
 return <main className="news-site"><NewsHeader event={event} section={section}/><div className="news-status"><b className="status-dot">●</b> {data?phases[data.phase]:'読み込み中'}<span>イベント時刻 {data?.clock||'—:—'} / 5秒ごと更新</span></div>{error&&<div className="error" role="alert">{error}。接続が戻ると自動で更新します。</div>}<div className="news-shell"><div className="news-main">
 {section==='ニュース'&&<><form className="news-search" onSubmit={e=>{e.preventDefault();setSearch(query);}}><input aria-label="ニュース検索" placeholder="グループ名・キーワードで記事を検索" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit">検索</button>{search&&<button type="button" onClick={()=>{setSearch('');setQuery('');}}>解除</button>}</form><div className="category-tabs">{['すべて',...categories].map((c:string)=><button className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><section className="topics-panel"><div className="news-section-title"><h2>{search?'検索結果':'芸能トピックス'}</h2><span>{news.length}件 / 確認済み記事</span></div>{featured?<div className="topics-grid"><ul>{news.slice(0,7).map((n:any,i:number)=><li key={n.id}><a href={articleHref(n,event)}>{n.headline}</a>{i===0&&<small className="new-label">NEW</small>}<span>{n.time} · {n.comments.length}コメント</span></li>)}</ul><a className="topic-feature" href={articleHref(featured,event)}><Artwork theme={featured.illustration} small/><strong>{featured.summary}</strong><small>週刊ケイテキ編集部</small></a></div>:<div className="news-empty"><Artwork theme="notice" small/><h3>{search?'一致する記事はありません':'まもなく、6組の物語が始まる。'}</h3><p>{search?'別のキーワードや分類で検索してください。':'運営が確認したニュースを掲載します。ファン数・GBは右側または専用ページで確認できます。'}</p></div>}</section><section className="feed-panel"><div className="news-section-title"><h2>新着ニュース</h2><span>記事ごとのURLでLINE共有</span></div>{news.map((n:any)=><a className="feed-row" key={n.id} href={articleHref(n,event)}><Artwork theme={n.illustration} small/><div><span className="news-category">{n.category}</span><h3>{n.headline}</h3><p>{n.summary}</p><small>週刊ケイテキ編集部 / {n.time} 配信 · {n.comments.length}コメント</small></div></a>)}</section></>}
 {section==='ファン数・GB'&&<section className="participant-panel"><div className="news-section-title"><h2>6グループのファン数・GB</h2><span>途中経過</span></div>{data&&<Rankings teams={data.teams}/>}<p className="footnote">GB残高は全組公開。途中順位は会場を回った数にも影響します。武道館点は全組終了後に公開します。</p></section>}
 {section==='チームの予定'&&<section className="participant-panel"><h2>自分たちのツアー予定</h2><label>グループ<select value={team} onChange={e=>setTeam(e.target.value)}>{rules.teams.map((t:any)=><option key={t.id} value={t.id}>{data?.teams.find((x:any)=>x.id===t.id)?.name||t.name}</option>)}</select></label><ol className="route-list">{rules.routes[Number(team.slice(1))-1].map((v:string,i:number)=><li key={i}><b>{Math.floor((930+i*15)/60)}:{String((930+i*15)%60).padStart(2,'0')}</b><div><strong>{v==='FREE'?'移動・自由活動':rules.venues.find((x:any)=>x.id===v)?.theme}</strong><p>{v==='FREE'?'次の会場への移動を優先。ミッション・合同ロケは余裕のある時間に。':rules.venues.find((x:any)=>x.id===v)?.name||'会場 '+v}</p></div></li>)}</ol><div className="team-banner">17:10 お題申請締切 → 17:20 共用棟集合・取引締切 → 17:30 武道館ライブ</div><p>アイドルと古参ファンは一緒に行動。会場受入は1枠1組です。会場間の徒歩時間は実地確認待ちです。</p></section>}
 {section==='ルール'&&<section className="participant-panel"><h2>推しを育てて、武道館へ。</h2><p>初期資金は600GB。稼いだGBを活動に使い、獲得ファン数で優勝を決めます。全員が輝くことも武道館の審査項目です。</p><h3>稼ぐ</h3><table><thead><tr><th>活動</th><th>報酬</th></tr></thead><tbody>{rules.missions.map((m:any)=><tr key={m.id}><td>{m.name}</td><td>{m.gb}GB{m.fans>0?' ＋'+man(m.fans):''}</td></tr>)}</tbody></table><h3>使う</h3><table><thead><tr><th>活動・購入</th><th>料金 / 上限</th></tr></thead><tbody>{rules.products.map((p:any)=><tr key={p.id}><td>{p.name}{p.fans>0?' ＋'+man(p.fans):''}</td><td>{p.price}GB / {p.max}回</td></tr>)}</tbody></table><h3>スキャンダルは各組1回</h3><p>16:00 チーム別予告、16:45 対応締切、16:50 結果記事を公開。もみ消し200GB / 釈明成功＋2万人 / 話題化成功＋3万人 / 失敗・未対応−3万人（下限0人）。疑惑はすべて架空の演出です。</p><h3>合同ロケ・SNS</h3><p>合同ロケは各組1回、各組300GBと3万人。SNSは承認1件1万人、投稿合計で各組4万人まで。</p><h3>武道館ライブ</h3><p>3審査員・5項目、合計60点。1点につきファン1万人。全組終了後に反映します。同ファン数なら武道館点、さらに同点なら「全アイドルが輝いているか」、なお同点なら同時デビュー。</p><p className="footnote">料金・報酬・詳細条件は試運転用の仮案です。最新の共通ルールは企画資料で管理します。</p></section>}
 </div><aside className="news-aside"><section className="aside-box"><div className="news-section-title"><h2>人気グループランキング</h2><span>LIVE</span></div>{data?<Rankings teams={data.teams} compact/>:<p>記録を読み込み中…</p>}<a className="aside-more" href={(portalHref(event))+'#ranking'}>ファン数・GBを詳しく見る →</a></section><section className="live-card"><small>KEITEKI SPECIAL LIVE</small><strong>17:30</strong><h3>最後の舞台は、武道館。</h3><p>恵迪寮 共用棟<br/>17:20までに全員集合</p></section><section className="aside-box"><h3>現場メモ</h3><p>全チームのGBを公開。記事・コメントは架空の演出で、コメント数や反応数は勝敗に影響しません。</p><p>困ったときはチームLINEで森本へ。</p></section></aside></div><NewsFooter/></main>;
}
