'use client';
import { useState } from 'react';
import { articleHref,categories,normalizeArticle } from '../../lib/articles.mjs';
import { commentDraft } from '../../lib/news-content.mjs';
export default function NewsDesk({snapshot,event,reload}:any){const [selected,setSelected]=useState<any>(null),[draft,setDraft]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all');
 function edit(n:any){if(draft&&JSON.stringify(draft)!==JSON.stringify(selected)&&!confirm('未保存の編集があります。選択を切り替えますか？'))return;setSelected(n);setDraft(structuredClone(n));setMessage('');}
 function create(){edit({id:'new',create:true,revision:0,headline:'',summary:'',body:'',category:'活動',illustration:'stage',teamIds:[],comments:commentDraft('mixed'),private:false,published:false,time:snapshot.clock});}
 async function save(status:string){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/articles?event='+event,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,status})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.article);setDraft(structuredClone(d.article));setMessage(status==='share'?'チーム用リンクを発行しました':status==='publish'?'全体に公開しました':'下書きを保存しました。公開・共有は停止中です');await reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function copy(){const n=selected;if(!n?.published&&!n?.sharedAt){setMessage('確認して公開、またはチーム用リンクを発行してからコピーしてください');return;}try{const link=new URL(articleHref(n,event,true),location.origin).href;await navigator.clipboard.writeText(`${event==='production'?'':'【練習用】'}${n.private?'【'+n.teamIds.join('・')+'限定／全体に転送しない】':''}${n.headline}\n${link}`);setMessage('見出しと記事URLをコピーしました。森本が対象のLINEへ投稿してください');}catch{setMessage('コピーできません。表示した記事URLを選択してコピーしてください');}}
 return <section className="content"><div className="section-heading"><h2>ニュース編集部</h2><button className="primary" onClick={create}>＋ 記事を作る</button></div><p>原稿・コメントを確認して公開。全体LINEには公開記事のURL、予告は対象チームだけに共有します。</p><div className="desk-grid"><aside className="desk-list"><label>記事を絞る<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">すべて</option><option value="draft">下書き</option><option value="public">全体公開</option><option value="team">チーム限定</option></select></label>{[...snapshot.raw.news].reverse().filter((n:any)=>filter==='all'||filter==='draft'&&!n.published&&!n.sharedAt||filter==='public'&&n.published||filter==='team'&&n.private).map((n:any)=><button className={draft?.id===n.id?'chosen':''} key={n.id} onClick={()=>edit(normalizeArticle(n))}><small>{n.private?(n.sharedAt?'チーム共有中':'チーム予告・下書き'):n.published?'全体公開中':'下書き'} / {n.time}</small><strong>{n.headline}</strong></button>)}{!snapshot.raw.news.length&&<p>活動を記録すると原稿が増えます。</p>}</aside><div className="desk-editor">{draft?<><div className="section-heading"><h3>{draft.private?'チーム限定の掲載予告':'全体向けの記事'}</h3><small>原稿版 {draft.revision}</small></div>{draft.create&&<label>公開先<select value={draft.private?'team':'all'} onChange={e=>setDraft({...draft,private:e.target.value==='team',teamIds:e.target.value==='team'?['G1']:[]})}><option value="all">全体向け</option><option value="team">1チーム限定の予告</option></select></label>}
 {draft.private&&<label>対象チーム<select disabled={!draft.create} value={draft.teamIds[0]||'G1'} onChange={e=>setDraft({...draft,teamIds:[e.target.value]})}>{snapshot.teams.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 <label>見出し（100字）<input value={draft.headline} maxLength={100} onChange={e=>setDraft({...draft,headline:e.target.value})}/></label><label>要約（180字・LINEでの表示にも使用）<textarea rows={2} value={draft.summary} maxLength={180} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><div className="two-columns"><label>分類<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map((c:string)=><option key={c}>{c}</option>)}</select></label><label>記事の挿絵<select value={draft.illustration} onChange={e=>setDraft({...draft,illustration:e.target.value})}>{Object.entries({stage:'ステージ',scandal:'掲載予告',collab:'合同ロケ',award:'受賞',notice:'お知らせ'}).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><label>本文（6000字）<textarea className="article-body-input" value={draft.body} maxLength={6000} onChange={e=>setDraft({...draft,body:e.target.value})}/></label>
 <h3>架空のコメント</h3><p className="footnote">コメントと反応数は演出です。得点には影響しません。本人の容姿・属性・実在の噂への攻撃は避け、活動へのツッコミとして確認してください。</p><div className="button-row">{[['mixed','応援・考察・辛口'],['supportive','応援中心'],['spicy','辛口あり']].map(([s,l])=><button key={s} onClick={()=>{if(confirm('現在のコメントを原案で置き換えますか？'))setDraft({...draft,comments:commentDraft(s,draft.headline,snapshot.teams.find((t:any)=>t.id===draft.teamIds[0])?.name)});}}>{l}の原案</button>)}</div>{draft.comments.map((c:any,i:number)=><fieldset className="comment-edit" key={c.id}><legend>コメント {i+1}</legend><div className="two-columns"><label>表示名<input maxLength={30} value={c.author} onChange={e=>setDraft({...draft,comments:draft.comments.map((x:any,j:number)=>i===j?{...x,author:e.target.value}:x)})}/></label><label>種類<select value={c.stance} onChange={e=>setDraft({...draft,comments:draft.comments.map((x:any,j:number)=>i===j?{...x,stance:e.target.value}:x)})}>{['応援','考察','辛口'].map(l=><option key={l}>{l}</option>)}</select></label></div><textarea aria-label={'コメント'+(i+1)+'本文'} maxLength={250} value={c.text} onChange={e=>setDraft({...draft,comments:draft.comments.map((x:any,j:number)=>i===j?{...x,text:e.target.value}:x)})}/><button onClick={()=>setDraft({...draft,comments:draft.comments.filter((_:any,j:number)=>i!==j)})}>このコメントを削除</button></fieldset>)}
 <div className="button-row sticky-actions"><button disabled={busy} onClick={()=>save('draft')}>下書き保存・公開停止</button><button disabled={busy} className="primary" onClick={()=>save(draft.private?'share':'publish')}>{draft.private?'確認してチーム用リンク発行':'確認して全体公開'}</button>{!draft.create&&<a href={'/admin/preview/'+encodeURIComponent(draft.id)+'?event='+event} target="_blank" rel="noreferrer">保存済み原稿のプレビュー ↗</a>}<button disabled={busy||(!selected?.published&&!selected?.sharedAt)} onClick={copy}>LINE用の見出し＋URL</button></div>{(selected?.published||selected?.sharedAt)&&<p className="link-output"><a href={articleHref(selected,event,true)} target="_blank" rel="noreferrer">{articleHref(selected,event,true)}</a></p>}{!draft.create&&<button onClick={()=>{const latest=snapshot.raw.news.find((n:any)=>n.id===draft.id);if(latest&&confirm('入力を破棄して保存済み原稿を読み直しますか？')){setSelected(normalizeArticle(latest));setDraft(structuredClone(normalizeArticle(latest)));}}}>保存済み原稿を読み直す</button>}{message&&<div role="status" className="notice">{message}</div>}</>:<p>左の記事を選んで編集するか、新しく記事を作成してください。</p>}</div></div></section>;
}
