import rules from './rules.json' with { type: 'json' };
export { rules };
export const PHASES = ['preparing','tour','closed','live','announced'];
export function minutes(t) { if(!/^\d{2}:\d{2}$/.test(t)) throw Error('時刻はHH:mmで入力してください'); const [h,m]=t.split(':').map(Number);if(h>23||m>59)throw Error('時刻が不正です');return h*60+m; }
function assert(ok,msg){if(!ok)throw Error(msg);}
function int(n,min,max){assert(Number.isInteger(n)&&n>=min&&n<=max,`数値は${min}〜${max}の整数です`);return n;}
function scores(arr,maxima){assert(Array.isArray(arr)&&arr.length===maxima.length,'採点項目数が違います');return arr.map((x,i)=>int(x,0,maxima[i]));}
export function emptyState(){return {phase:'preparing',clock:'15:00',teams:rules.teams.map(t=>({...t})),actions:[],news:[]};}
export function demonstration(){const s=emptyState();s.actions.push({id:'seed-phase',kind:'phase',value:'tour',time:'15:00'});for(let i=0;i<6;i++)s.actions.push({id:`seed-stage-${i}`,kind:'stage',teamId:`G${i+1}`,venue:'A',scores:[3+(i%2),3,4,5+(i%3)],time:'15:35'});s.actions.push({id:'seed-work',kind:'mission',teamId:'G2',missionId:'work1',time:'15:40'},{id:'seed-ad',kind:'purchase',teamId:'G1',productId:'ad',time:'15:45'},{id:'seed-clock',kind:'clock',value:'16:00',time:'16:00'});s.news.push({id:'welcome',headline:'恵迪寮発、6組のアイドルがツアーへ',body:'これは操作確認用の練習データです。実際の参加結果ではありません。全チームのGBとファン数を一覧で確認できます。',published:true,time:'15:00'});return s;}
export function calculate(state){
 const voided=new Set(state.actions.filter(a=>a.kind==='void'||a.kind==='replace').map(a=>a.targetId));
 const teams=Object.fromEntries(state.teams.map(t=>[t.id,{...t,gb:t.initialGb,fans:0,stages:{},purchases:{},missions:{},sns:[],scandal:null,final:null}]));
 let phase='preparing',clock='15:00',settled=false,scandalPublished=false;const effects=[];
 for(const original of state.actions){if(original.kind==='void'||voided.has(original.id))continue;const a=original.kind==='replace'?{...original.replacement,id:original.id,time:original.time,reason:original.reason}:original;const t=teams[a.teamId];let gb=0,fans=0,label=a.kind;
  if(['stage','mission','purchase','sns','scandal_open','scandal_resolve','final','adjust'].includes(a.kind))assert(t,'グループが不正です');
  if(a.kind==='phase'){assert(PHASES.includes(a.value),'進行段階が不正です');phase=a.value;}
  else if(a.kind==='clock'){minutes(a.value);clock=a.value;}
  else if(a.kind==='stage'){const v=rules.venues.find(v=>v.id===a.venue);assert(v,'会場が不正です');assert(!t.stages[v.id],'この会場は採点済みです');const sc=scores(a.scores,v.maxima);t.stages[v.id]=sc;fans=sc.reduce((n,x)=>n+x,0)*10000;label=v.theme+'ステージ';}
  else if(a.kind==='mission'){const m=rules.missions.find(m=>m.id===a.missionId);assert(m,'ミッションが不正です');assert(!t.missions[m.id],'このミッションは受取済みです');t.missions[m.id]=true;gb=m.gb;fans=m.fans;label=m.name;}
  else if(a.kind==='collab'){assert(Array.isArray(a.teamIds)&&a.teamIds.length===2&&a.teamIds[0]!==a.teamIds[1],'異なる2組を選んでください');for(const id of a.teamIds){const c=teams[id];assert(c&&!c.missions.collab,'合同ロケは各組1回です');c.missions.collab=true;c.gb+=300;c.fans+=30000;}label='合同ロケ';}
  else if(a.kind==='purchase'){const p=rules.products.find(p=>p.id===a.productId);assert(p,'商品が不正です');assert((t.purchases[p.id]||0)<p.max,'購入上限です');assert(!p.proofRequired||a.proof?.trim(),'成功の確認内容が必要です');assert(t.gb>=p.price,'GB残高が足りません');t.purchases[p.id]=(t.purchases[p.id]||0)+1;gb=-p.price;fans=p.fans;label=p.name;}
  else if(a.kind==='sns'){assert(['idol','fan'].includes(a.postType),'投稿の種類を選んでください');assert(a.proof?.trim(),'投稿内容・確認根拠が必要です');if(a.postType==='idol'){const prev=t.sns.filter(p=>p.postType==='idol').at(-1);assert(!prev||minutes(a.time)-minutes(prev.time)>=15,'アイドル投稿は15分に1回です');}else{assert(rules.venues.some(v=>v.id===a.venue),'ライブ報告の会場を選んでください');assert(t.stages[a.venue],'会場の採点後にライブ報告できます');assert(!t.sns.some(p=>p.postType==='fan'&&p.venue===a.venue),'この会場のライブ報告は受理済みです');}fans=t.sns.length<rules.sns.maxBonusPostsPerTeam?10000:0;t.sns.push({...a});label='SNS掲載';}
  else if(a.kind==='scandal_open'){assert(!t.scandal,'スキャンダルは各組1回です');t.scandal={topic:rules.scandal.topics[Number(t.id.slice(1))-1],resolution:null};label='掲載予告';}
  else if(a.kind==='scandal_resolve'){assert(t.scandal&&!t.scandal.resolution,'未対応の予告が必要です');assert(['cover','apology','publicity','failed'].includes(a.resolution),'対応が不正です');assert(a.resolution==='cover'||a.proof?.trim(),'確認内容が必要です');if(a.resolution==='cover'){assert(t.gb>=200,'口止め料200GBが足りません');gb=-200;}t.scandal.resolution=a.resolution;label='スキャンダル対応';}
  else if(a.kind==='scandal_publish'){assert(!scandalPublished,'結果は公開済みです');assert(Object.values(teams).every(t=>t.scandal),'全6組の予告が必要です');for(const c of Object.values(teams)){const mode=c.scandal.resolution||'ignored',delta=mode==='cover'?0:mode==='apology'?20000:mode==='publicity'?30000:-30000;c.fans=Math.max(0,c.fans+delta);c.scandal.published=true;c.scandal.result=delta;}scandalPublished=true;label='スキャンダル結果公開';}
  else if(a.kind==='settle'){assert(!settled,'17時の定期収入は清算済みです');for(const c of Object.values(teams)){let x=0;if(c.missions.sponsor)x+=rules.income.sponsorGb;if(c.missions.fanclub)x+=Math.min(300,Math.floor(c.fans/100000)*50);c.gb+=x;c.income=x;}settled=true;label='17時定期収入';}
  else if(a.kind==='final'){assert(!t.final,'武道館は採点済みです');assert(Array.isArray(a.judges)&&a.judges.length===3,'審査員3人の採点が必要です');const all=a.judges.map(j=>scores(j,rules.final.maxima)),avg=rules.final.maxima.map((_,i)=>all.reduce((s,r)=>s+r[i],0)/3),total=Math.round(avg.reduce((s,x)=>s+x,0)*10)/10;t.final={judges:all,averages:avg,total,fans:Math.round(total*10000)};label='武道館採点（公開待ち）';}
  else if(a.kind==='adjust'){assert(a.reason?.trim().length>=4,'訂正の理由を4文字以上で入力してください');gb=int(a.gb,-10000,10000);fans=int(a.fans,-10000000,10000000);label='手動訂正';}
  else throw Error('不明な操作です');
  if(t){t.gb+=gb;t.fans=Math.max(0,t.fans+fans);assert(t.gb>=0,'訂正すると残高がマイナスになります。関連する購入を先に取り消してください');}
  effects.push({id:a.id,teamId:a.teamId,teamIds:a.teamIds,kind:a.kind,label,gb,fans,time:a.time,reason:a.reason||a.proof||''});
 }
 if(phase==='announced')assert(Object.values(teams).every(t=>t.final),'全6組の武道館採点が必要です');
 const ordered=Object.values(teams).map(t=>({...t,totalFans:t.fans+(phase==='announced'?(t.final?.fans||0):0)})).sort((a,b)=>b.totalFans-a.totalFans||(phase==='announced'?((b.final?.total||0)-(a.final?.total||0)||(b.final?.averages[3]||0)-(a.final?.averages[3]||0)):0)||a.id.localeCompare(b.id));
 let prev=null,rank=0;ordered.forEach((t,i)=>{const key=[t.totalFans,phase==='announced'?t.final?.total:0,phase==='announced'?t.final?.averages[3]:0].join(':');if(key!==prev)rank=i+1;t.rank=rank;prev=key;});
 return {teams:ordered,phase,clock,settled,scandalPublished,effects,voided:[...voided]};
}
export function append(state,input){assert(input&&typeof input==='object','操作を指定してください');assert(!state.actions.some(a=>a.id===input.id),'同じ操作は登録済みです');const current=calculate(state),a={...input,id:input.id||crypto.randomUUID(),time:input.time||current.clock};minutes(a.time);
 if(!['phase','clock','void','adjust','final','replace'].includes(a.kind)){assert(current.phase==='tour','この操作はツアー中に行います');assert(minutes(a.time)<minutes('17:20'),'取引は17:20で締切です');}
 if(a.kind==='replace'){const old=state.actions.find(x=>x.id===a.targetId),oldKind=old?.kind==='replace'?old.replacement.kind:old?.kind;assert(old&&!current.voided.includes(old.id)&&['stage','final'].includes(oldKind),'訂正する有効な採点を選んでください');assert(a.reason?.trim().length>=4,'訂正理由を4文字以上で入力してください');assert(a.replacement?.kind===oldKind&&a.replacement?.teamId===(old?.teamId||old?.replacement?.teamId),'同じ種類・チームの採点だけ訂正できます');if(oldKind==='stage')assert(a.replacement.venue===(old.venue||old.replacement?.venue),'同じ会場の採点だけ訂正できます');}
 if(a.kind==='scandal_resolve')assert(minutes(a.time)<=minutes('16:45'),'対応は16:45で締切です');
 if(a.kind==='scandal_publish')assert(minutes(a.time)>=minutes('16:50'),'結果公開は16:50以降です');
 if(a.kind==='settle')assert(minutes(a.time)>=minutes('17:00'),'定期収入は17:00以降です');
 if(a.kind==='final')assert(current.phase==='live'&&minutes(a.time)>=minutes('17:30'),'武道館採点はライブ開始後です');
 if(a.kind==='phase'){const old=PHASES.indexOf(current.phase),next=PHASES.indexOf(a.value);assert(next===old+1,'進行段階は順番に進めてください');if(a.value==='closed'){assert(current.settled,'17時の定期収入を清算してください');assert(current.scandalPublished,'スキャンダル結果を公開してください');}}
 if(a.kind==='void'){const target=state.actions.find(x=>x.id===a.targetId);assert(target&&!['void','phase','clock'].includes(target.kind),'取り消せる取引を選んでください');assert(!current.voided.includes(a.targetId),'取り消し済みです');assert(a.reason?.trim().length>=4,'理由を4文字以上で入力してください');}
 const next={...state,actions:[...state.actions,a]};calculate(next);return next;
}
export function publicView(state){const c=calculate(state);return {phase:c.phase,clock:c.clock,teams:c.teams.map(({final,scandal,sns,...t})=>({...t,final:c.phase==='announced'?final:null,scandal:scandal?.published?scandal:null})),news:state.news.filter(n=>n.published),settled:c.settled,scandalPublished:c.scandalPublished};}
export function draftFor(a,state){const c=calculate(state),t=c.teams.find(t=>t.id===a.teamId),name=t?.name||'出演グループ',e=c.effects.find(e=>e.id===a.id);if(a.kind==='scandal_open')return {headline:`週刊ケイテキから${name}へ掲載予告`,body:`${t.scandal.topic}。16:45までに、もみ消し200GB、30秒の釈明、15秒の話題化から対応を選んでください。`,target:a.teamId,private:true};if(a.kind==='scandal_resolve')return null;if(a.kind==='final')return null;if(a.kind==='collab')return {headline:'ライバル2組、合同CMで共演',body:`${a.teamIds.map(id=>c.teams.find(t=>t.id===id)?.name).join('と')}が合同ロケを完了。各組に出演料300GB、新規ファン3万人を追加しました。`,target:'all'};if(a.kind==='scandal_publish')return {headline:'週刊ケイテキ、6組の対応結果を公開',body:c.teams.map(t=>`${t.name}：${({cover:'もみ消し',apology:'釈明',publicity:'話題化',failed:'対応失敗'})[t.scandal?.resolution]||'未対応'}。ファン変動${t.scandal?.result>=0?'+':''}${(t.scandal?.result||0)/10000}万人。`).join('\n'),target:'all'};if(a.kind==='phase'&&a.value==='announced')return {headline:`${c.teams.filter(t=>t.rank===1).map(t=>t.name).join('・')}がメジャーデビュー`,body:c.teams.map(t=>`${t.rank}位 ${t.name}：${(t.totalFans/10000).toFixed(1)}万人`).join('\n'),target:'all'};if(e&&t&&['stage','mission','purchase','sns'].includes(a.kind))return {headline:`${name}、${e.label}を完了`,body:`${e.label}の結果、GB変動${e.gb>=0?'+':''}${e.gb}GB、ファン変動${e.fans>=0?'+':''}${e.fans/10000}万人。確認済みの活動内容をここに追記してください。`,target:'all'};return null;}
