import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const rules=JSON.parse(fs.readFileSync(path.join(root,'data/rules.json'),'utf8'));
const out=path.join(root,'materials/print');
fs.mkdirSync(out,{recursive:true});
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const css=`@page{size:A4;margin:13mm}*{box-sizing:border-box}body{font-family:'Yu Gothic','Meiryo',sans-serif;color:#152532;font-size:10pt;margin:0;line-height:1.55}h1{font-size:23pt;margin:0 0 4mm}h2{font-size:13pt;margin:5mm 0 2mm}h3{font-size:11pt;margin:3mm 0 1mm}p{margin:1.5mm 0}.page{break-after:page;min-height:262mm;padding:0;position:relative}.page:last-child{break-after:auto}.badge{font-size:9pt;display:inline-block;background:#102c3a;color:white;padding:1mm 3mm;margin-bottom:3mm}.lead{font-size:12pt;font-weight:bold;padding:3mm;background:#ecf5f7}.muted{color:#51636a;font-size:9pt}.footer{font-size:8pt;color:#51636a;border-top:1px solid #b5c7cb;margin-top:4mm;padding-top:2mm}table{width:100%;border-collapse:collapse;margin:2mm 0;font-size:9pt}th,td{border:1px solid #9cb2b8;text-align:left;padding:2mm;vertical-align:top}th{background:#edf4f5}.fill{height:11mm}.line{border-bottom:1px solid #6c7b80;display:inline-block;min-width:27mm;height:6mm}.grid{display:grid;grid-template-columns:1fr 1fr;gap:4mm}.card{border:1px solid #7d9ea8;padding:4mm;min-height:112mm;break-inside:avoid}ol,ul{padding-left:6mm;margin:2mm 0}li{margin:1mm 0}.big{font-size:34pt;font-weight:bold}.center{text-align:center}.signature{margin-top:3mm;display:flex;gap:8mm}.score td:nth-child(2){width:20mm}.check td:first-child{width:9mm}.small{font-size:9pt}.stage-sign h1{font-size:43pt}.stage-sign .lead{font-size:18pt}@media screen{body{background:#dbe5e7;padding:10mm}.page{background:white;max-width:184mm;min-height:269mm;padding:7mm;margin:0 auto 10mm;box-shadow:0 2px 10px #87989b}.card{background:white}}@media print{.toolbar{display:none}.page{box-shadow:none;margin:0}}`;
const html=(title,body)=>`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${css}</style></head><body><div class="toolbar"><p>A4印刷用。印刷前にプレビューでページ数を確認してください。</p></div>${body}</body></html>`;
const footer=`<div class="footer">アイドル駅伝｜2026-10-11 試運転版｜正式な時刻・金額・配置は本番前に確認</div>`;
const save=(file,title,body)=>fs.writeFileSync(path.join(out,file),html(title,body));
const prices=rules.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.price}GB</td><td>${p.fans?`${p.fans/10000}万ファン`:'使い方・実演を評価'}</td><td>${p.max}回</td></tr>`).join('');
save('participant-guide.html','参加者1枚ガイド',`<section class="page"><span class="badge">参加者用｜1枚</span><h1>推しと一緒に、武道館へ。</h1><p class="lead">一年目はアイドル。上の年目は古参ファン。<br>6チームで4会場を巡り、ファン数No.1を目指そう！</p><h2>今日の流れ</h2><ol><li><b>15:00 記者会見</b>：名前・色・ルートを確認し、撮影係／時間係／購入係を決める。</li><li><b>15:30〜17:00 ツアー</b>：Aお笑い／Bクイズ／Cスポーツ／Dダンスを指定ルートの順で訪問。自由枠は仕事と移動に。</li><li><b>16:00 架空スキャンダル</b>：16:45までに200GBで解決、30秒釈明、15秒CM／コントから選ぶ。</li><li><b>17:10 演目申告 → 17:20 共用棟集合</b>：衣装・装飾・音源を準備。</li><li><b>17:30 武道館ライブ</b>：各組3分。最後のファン数で優勝！</li></ol><h2>GBを稼いで、使う（ゲーム内通貨）</h2><p>初期<b>${rules.teams[0].initialGb}GB</b>。営業①〜③ 各200GB、スポンサーCM 300GB＋2万ファン、合同ロケ 300GB＋3万ファン、FC開設100GB。</p><table><tr><th>購入</th><th>価格</th><th>効果</th><th>上限</th></tr>${prices}</table><h2>アイドルも古参ファンも出番がある</h2><p>アイドルは出演・決めポーズ。古参ファンは撮影・応援・営業・衣装。演技と紹介は一年目全員に分ける。投稿や申告は「G番号／イベント名／写真・動画／購入品」をチームLINEへ。森本が質問に対応します。</p><p><b>1点＝1万ファン。</b> ツアー25点×4会場、武道館60点。GB・ファン数・順位は全体公開。SNSは承認1件＋1万、全投稿合計4件まで。衣装購入だけで点は付きません。</p><p class="muted">歩いてチームで移動。通行をふさがない場所で実演。撮影が難しい場合は運営へ実演で提出。遅れそうならチームLINEへ連絡。</p>${footer}</section>`);

const scoreRows=(criteria,maxima)=>criteria.map((c,i)=>`<tr><td>${esc(c)}</td><td>${maxima[i]}点</td><td class="fill"></td><td></td></tr>`).join('');
let scoring=rules.venues.map(v=>`<section class="page"><span class="badge">ツアー採点｜${v.id}</span><h1>${esc(v.name)}</h1><p>テーマ：${esc(v.theme)} ／担当：${esc(v.staff)} ／満点25点</p><p>チーム <span class="line"></span> 時刻 <span class="line"></span> 受付番号 <span class="line"></span></p><table class="score"><tr><th>項目</th><th>上限</th><th>得点</th><th>観察メモ</th></tr>${scoreRows(v.criteria,v.maxima)}<tr><th>合計</th><th>25点</th><td class="fill"></td><td>ファン増加：得点×1万人</td></tr></table><h2>採点の目安（仮・全会場共通）</h2><table><tr><th>5点項目</th><th>10点項目</th><th>目安</th></tr><tr><td>0</td><td>0</td><td>未実施。運営都合の未実施は森本に相談</td></tr><tr><td>1〜2</td><td>1〜4</td><td>一部は達成、参加や完成が限定的</td></tr><tr><td>3</td><td>5〜6</td><td>基本条件を達成、全体に伝わる</td></tr><tr><td>4</td><td>7〜8</td><td>工夫があり、複数人が活躍</td></tr><tr><td>5</td><td>9〜10</td><td>条件を十分に達成、工夫と一体感がある</td></tr></table><p>ビジュアルは衣装価格・購入数ではなく、色のまとまりと見せ方を評価。かしこさや競技は事前に決めた正答数・測定結果を使う。同一項目で審査基準を途中変更しない。</p><h2>送信前チェック</h2><p>□ G番号 □ 上限以内 □ 合計 □ 重複なし □ チームへ読上げ □ 森本へ送信</p><p>確定得点 <span class="line"></span> 台帳番号 <span class="line"></span></p><p>訂正理由・元記録番号：</p><div style="height:30mm;border:1px solid #9cb2b8"></div>${footer}</section>`).join('');
scoring+=`<section class="page"><span class="badge">武道館｜審査員1名につき1枚・合計18枚</span><h1>最終ライブ 採点票</h1><p>チーム <span class="line"></span> 出順 <span class="line"></span> 審査員 <span class="line"></span></p><p>演目 <span class="line"></span> 時刻 <span class="line"></span></p><table class="score"><tr><th>項目</th><th>上限</th><th>得点</th><th>観察メモ</th></tr>${scoreRows(rules.final.criteria,rules.final.maxima)}<tr><th>合計</th><th>60点</th><td class="fill"></td><td>3名の平均を採用する仮案</td></tr></table><h2>評価するもの</h2><p>全アイドルに出番があるか、応援との一体感、衣装と色の見せ方、内容の工夫。難しい技を選んだことだけで自動加点しない。10点項目は上の目安、15点項目は「基本達成8〜9／工夫あり10〜12／十分達成13〜15」の仮基準。</p><p>台帳へ送る：G番号／審査員番号／5項目／時刻／紙番号</p><h2>確認</h2><p>□ 5項目のみ □ 各上限 □ 60点以内 □ 同じチーム3名揃った □ 集計後二者確認</p><p>3名の各項目平均を合計し、小数第1位に一度だけ丸める仮案。合計×1万ファンを1回加算。項目ごとには丸めず、ツアー25点をさらに加えない。</p><p>受賞の同点：武道館合計 → 全員が輝く項目 → 同時デビュー（仮）。</p>${footer}</section>`;
save('score-sheets.html','ツアー・最終ライブ採点票',scoring);
const header=['チーム','会場','審査員','時刻','項目1','項目2','項目3','項目4','項目5','合計','紙番号','台帳番号','備考'];
const scoreCsv=[header,...rules.teams.flatMap(t=>rules.venues.map(v=>[t.id,v.id,v.staff,'','','','','','','','','',''])),...rules.teams.flatMap(t=>[1,2,3].map(n=>[t.id,'FINAL',`審査員${n}`,'','','','','','','','','','']))];
assert.equal(scoreCsv.length,43);
fs.writeFileSync(path.join(out,'score-sheets.csv'),'\ufeff'+scoreCsv.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n')+'\r\n');
const blankRows=Array.from({length:12},()=>'<tr><td class="fill"></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>').join('');
save('reception-ledger.html','通信断時の受付台帳',`<section class="page"><span class="badge">紙の予備台帳｜受付番号は重複させない</span><h1>イベント・購入 受付台帳</h1><p>日付 <span class="line"></span> 担当 <span class="line"></span> ページ <span class="line"></span></p><table><tr><th>番号／時刻</th><th>G</th><th>内容・成否</th><th>GB増減</th><th>ファン増減</th><th>証拠・担当</th><th>入力済✓</th></tr>${blankRows}</table><p>購入前残高を確認。現物を渡したら番号を記録。入力済み欄に✓を付ける。訂正は二重線と理由を残す。スキャンダルのファン増減は16:50一括、17:00定期入金は1回。</p><p>保存版の番号 <span class="line"></span> 森本確認 <span class="line"></span></p>${footer}</section>`);
const start=15*60+30;
const time=m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`;
save('team-routes.html','6チームルート札',rules.teams.map((t,i)=>`<section class="page"><span class="badge" style="background:${t.color};color:#152532">${t.id}｜チームルート</span><h1>${esc(t.name)}</h1><p>正式グループ名 <span class="line" style="min-width:85mm"></span></p><p class="lead">15:00開始｜17:10演目申告｜17:20共用棟集合｜17:30開演</p><table><tr><th>受付枠</th><th>行き先</th><th>やること</th><th>完了✓</th></tr>${rules.routes[i].map((id,j)=>{const v=rules.venues.find(v=>v.id===id);return `<tr><td>${time(start+j*15)}〜${time(start+(j+1)*15)}</td><td>${v?`${id} ${esc(v.name)}`:'自由・移動'}</td><td>${v?esc(v.theme):'仕事・衣装・ロケ・移動。次の会場へ間に合う範囲で。'}</td><td></td></tr>`}).join('')}</table><h2>受信・申告</h2><p>16:00スキャンダル予告 → 16:45対応締切 → 16:50結果。17:00ツアー終了・定期入金。</p><p>撮影係 <span class="line"></span> 時間係 <span class="line"></span> 購入係 <span class="line"></span></p><h2>投稿欄</h2><p>チームLINE確認 □　ダッシュボードURL／QR：本番の公開先確定後に記入</p><div style="height:35mm;border:1px dashed #9cb2b8"></div><p class="muted">徒歩時間は実測前。次の受付に間に合わないときは走らずチームLINEで森本へ連絡。</p>${footer}</section>`).join(''));
save('stage-signs.html','会場案内札',rules.venues.map(v=>`<section class="page stage-sign center"><span class="badge">アイドル駅伝｜会場${v.id}</span><div class="big">${v.id}</div><h1>${esc(v.theme)}</h1><p class="lead">${esc(v.name)}<br>担当 ${esc(v.staff)}</p><h2>1会場1チーム／指定時刻に受付</h2><table><tr><th>時刻</th><th>チーム</th></tr>${Array.from({length:6},(_,j)=>`<tr><td>${time(start+j*15)}</td><td>${rules.teams[rules.routes.findIndex(route=>route[j]===v.id)].id}</td></tr>`).join('')}</table><p>実施・採点5分＋次の場所へ移動10分（仮）</p><p>到着したらチーム番号を担当へ伝えてください。</p><p>通行の妨げにならない場所で待機してください。</p>${footer}</section>`).join('')+`<section class="page stage-sign center"><span class="badge">本部｜共用棟</span><h1>武道館</h1><p class="lead">17:20 全員集合<br>17:30 ケイテキスペシャルライブ</p><h2>購入・申告：小峰<br>全体PC・質問：森本</h2><p>17:10 演目申告終了<br>17:20 購入終了・出順確定</p><p>GBとファン数の記録は台帳で確認してください。</p>${footer}</section>`);
const events=[
 ['営業①｜200GB','推しの魅力を3つ、30秒で紹介。古参ファン2名以上が発言、アイドルが決めポーズ。','2分／各組1回'],
 ['営業②｜200GB','アイドルが3つの簡単なポーズ。古参ファンが同じ順に再現。座ったまま・上半身でも可。','2分／各組1回'],
 ['営業③｜200GB','名前と決め台詞を含む10秒応援コール。古参ファン複数人が参加。','2分／各組1回'],
 ['スポンサー｜300GB＋2万','ケイテキソーダCM15秒。「ひらめき・推し・ケイテキ」を含め、アイドル出演。17:00に200GBを1回入金。','3分／各組1回'],
 ['合同ロケ｜各300GB＋3万','2組で自己紹介、相手の魅力、最後は「推しは違っても、舞台は一緒！」。15秒ずつ動画リレーでも可。両方の確認後に成立。','4分／各組1回'],
 ['FC開設｜100GB','ファンクラブ名・応援合言葉・全アイドル紹介を1枚に。17:00に10万ファンごと50GB、最大300GBを1回入金。','2分／各組1回'],
 ['スキャンダル｜全組1回','200GBで解決：増減0。30秒釈明：「まず・実は・これから」で説明と宣言、＋2万。15秒CM／コント：疑惑とグループ名、＋3万。失敗・未対応は−3万。','16:00予告／16:45締切／16:50反映'],
 ['SNS｜承認1件＋1万','写真か短文でアイドル・ファンの働きを紹介。アイドル15分に1回、ファン会場レポは会場ごと1回。合算4件・4万まで。','全SNS・レポ合算。別作品を提出']
];
let cards='';
for(let i=0;i<events.length;i+=4) cards+=`<section class="page"><span class="badge">受付イベントカード｜条件は全組共通</span><h1>番組の仕事・広報対応</h1><div class="grid">${events.slice(i,i+4).map(e=>`<article class="card"><h2>${esc(e[0])}</h2><p class="muted">${esc(e[2])}</p><p>${esc(e[1])}</p><p>G番号 <span class="line"></span></p><p>確認者 <span class="line"></span></p><p>受付番号 <span class="line"></span></p><p>時刻 <span class="line"></span></p><p>□成立 □要確認 □台帳入力済み</p></article>`).join('')}</div>${footer}</section>`;
save('event-cards.html','仕事・広報イベントカード',cards);
const checklist=['チームとG番号','6組の初期600GB・ファン0','スタッフと司会交代','徒歩・雨天・会場条件','ニュース差込と公開了承','紙票と受付番号','17:00入金1回','17:10演目・17:20帰還','最終採点3名×6組','訂正・同点処理','確定台帳バックアップ','借用品返却・実費精算'];
save('operations-checklist.html','運営チェック1枚',`<section class="page"><span class="badge">運営共通｜1枚</span><h1>本番チェック</h1><p>日付 <span class="line"></span> 担当 <span class="line"></span></p><table class="check"><tr><th>✓</th><th>確認</th><th>担当・時刻・メモ</th></tr>${checklist.map(s=>`<tr><td class="fill"></td><td>${esc(s)}</td><td></td></tr>`).join('')}</table><p>入力：森本／照合・購入：小峰／固定Aたけ B佐伯 Cぷし Dやり／南アレックス 北侍 巡回アツコン。</p><p>開始司会：ボンボ・グッドマン → 16:30交代仮案 → 最後司会：シャネル・スーダン。名簿13人・同時最大11人。</p><p>通信断：紙に時刻・番号・GB・ファン・担当を記録。復旧後の二重登録を防ぐ。</p>${footer}</section>`);
fs.writeFileSync(path.join(out,'README.md'),`# A4印刷セット\n\n2026-10-11 試運転版。HTMLをブラウザで開いて印刷できます。\n\n- participant-guide.html：参加者1枚。60人分または各チーム数枚。\n- team-routes.html：6組のルート札、各1枚。\n- score-sheets.html：ツアー4会場と武道館の空欄票。ツアー各会場6枚、武道館18枚。\n- score-sheets.csv：24ツアー＋18武道館＝42行の記入欄。\n- reception-ledger.html：通信断用台帳。数枚。\n- stage-signs.html：4会場＋本部の5枚。\n- event-cards.html：仕事・スキャンダル・SNSの8カード、2ページ。\n- operations-checklist.html：運営1枚。\n- live-order.html：武道館演目申告・出順・音源確認の別紙2ページ。PDFは../../output/pdf/live-order.pdf。\n\n印刷PDF冊子：../../output/pdf/print-pack.pdf（21ページ・種類別しおり）。ページ1：参加者、2〜7：ルート、8〜11：ツアー採点、12：最終採点、13：受付台帳、14〜18：会場札、19〜20：イベントカード、21：運営チェック。必要なページを必要枚数印刷してください。\n\n生成元：scripts/build-print.mjs。ルール変更後は再生成してください。A4・倍率100%・ヘッダー/フッターなしでプレビュー確認。CSSは印刷用ですが、ブラウザやフォントによってページ分割は変わるため、本番印刷前に確認してください。公開先URL/QRは公開方法確定後に記入します。\n`);
process.stdout.write(JSON.stringify({printFiles:fs.readdirSync(out),csvRows:scoreCsv.length-1, rulesVersion:rules.version},null,2)+'\n');
